version: "3.8"

services:
    mysql1:
        image: mysql
        container_name: mysql1
        volumes:
            - ./conf/master1.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 127.0.0.1:3306:3306
        networks:
            - replication
    mysql2:
        image: mysql
        container_name: mysql2
        volumes:
            - ./conf/master2.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 127.0.0.1:3307:3306
        networks:
            - replication
    db_maintenance:
        build:
            ./DBMaintenance
        container_name: db_maintenance
        ports:
            - 127.0.0.1:40666:40666
        networks:
            - replication
    discovery:
        build:
            ./Discovery
        container_name: discovery
        ports:
            - 127.0.0.1:40404:40404
            - 127.0.0.1:40405:40405
        networks:
            - replication
    scrapper:
        build:
            ./Service/Scrapper
        container_name: scrapper
        ports:
            - 127.0.0.1:40555:40555
        networks:
            - replication
        depends_on:
            - discovery
networks:
    replication:
        name: replication
