version: "3.8"

services:
    mysql1:
        image: mysql
        container_name: mysql1
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 127.0.0.1:3306:3306
        networks:
            - replication
    mysql2:
        image: mysql
        container_name: mysql2
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 127.0.0.1:3307:3306
        networks:
            - replication
    db_maintenance:
        build:
            ./DBMaintenance
        container_name: db_maintenance
        ports:
            - 127.0.0.1:40666:40666
        networks:
            - replication
networks:
    replication:
        name: replication
